/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "block-sign-in": lazyRegistryComponent(
    () => import("@/registry/blocks/sign-in/sign-in-1/index.tsx"),
    {"title":{"value":"Welcome back"},"description":{"value":"Enter your credentials to access your account"},"buttonText":{"value":"Sign In"},"variant":{"value":"default","options":{"Default":"default","Elevated":"elevated","Bordered":"bordered","Soft":"soft"}},"buttonVariant":{"value":"default","options":{"Default":"default","Outline":"outline","Secondary":"secondary","Ghost":"ghost"}},"cardWidth":{"value":384,"min":280,"max":600,"step":8},"borderRadius":{"value":16,"min":0,"max":32,"step":2},"padding":{"value":24,"min":12,"max":48,"step":4},"socialColumns":{"value":2,"options":{"1 Column":1,"2 Columns":2}},"maxAttempts":{"value":5,"min":0,"max":10,"step":1},"showSocials":{"value":true},"showRememberMe":{"value":true},"showForgotPassword":{"value":true}},
  ),
};
