/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "components-spaceui-data-grid": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/data-grid/data-grid/index.tsx"),
    {},
  ),
  "components-spaceui-data-grid-column-filter": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/data-grid/data-grid-column-filter/index.tsx"),
    {},
  ),
  "components-spaceui-data-grid-column-header": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/data-grid/data-grid-column-header/index.tsx"),
    {},
  ),
  "components-spaceui-data-grid-column-visibility": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/data-grid/data-grid-column-visibility/index.tsx"),
    {},
  ),
  "components-spaceui-data-grid-pagination": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/data-grid/data-grid-pagination/index.tsx"),
    {},
  ),
  "components-spaceui-data-grid-scroll-area": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/data-grid/data-grid-scroll-area/index.tsx"),
    {},
  ),
  "components-spaceui-data-grid-table": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/data-grid/data-grid-table/index.tsx"),
    {},
  ),
  "components-spaceui-data-grid-table-dnd": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/data-grid/data-grid-table-dnd/index.tsx"),
    {},
  ),
  "components-spaceui-data-grid-table-dnd-rows": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/data-grid/data-grid-table-dnd-rows/index.tsx"),
    {},
  ),
  "components-spaceui-data-grid-table-virtual": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/data-grid/data-grid-table-virtual/index.tsx"),
    {},
  ),
};
