/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "components-spaceui-event-calendar": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/event-calendar/event-calendar/index.tsx"),
    {},
  ),
  "components-spaceui-event-calendar-agenda-view": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/event-calendar/event-calendar-agenda-view/index.tsx"),
    {},
  ),
  "components-spaceui-event-calendar-content": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/event-calendar/event-calendar-content/index.tsx"),
    {},
  ),
  "components-spaceui-event-calendar-dnd": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/event-calendar/event-calendar-dnd/index.tsx"),
    {},
  ),
  "components-spaceui-event-calendar-event": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/event-calendar/event-calendar-event/index.tsx"),
    {},
  ),
  "components-spaceui-event-calendar-i18n": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/event-calendar/event-calendar-i18n/index.tsx"),
    {},
  ),
  "components-spaceui-event-calendar-lib": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/event-calendar/event-calendar-lib/index.tsx"),
    {},
  ),
  "components-spaceui-event-calendar-month-view": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/event-calendar/event-calendar-month-view/index.tsx"),
    {},
  ),
  "components-spaceui-event-calendar-nav": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/event-calendar/event-calendar-nav/index.tsx"),
    {},
  ),
  "components-spaceui-event-calendar-recurrence": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/event-calendar/event-calendar-recurrence/index.tsx"),
    {},
  ),
  "components-spaceui-event-calendar-resource-view": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/event-calendar/event-calendar-resource-view/index.tsx"),
    {},
  ),
  "components-spaceui-event-calendar-time-grid": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/event-calendar/event-calendar-time-grid/index.tsx"),
    {},
  ),
  "components-spaceui-event-calendar-types": lazyRegistryComponent(
    () => import("@/registry/components/spaceui/event-calendar/event-calendar-types/index.tsx"),
    {},
  ),
};
