/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react'

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>
  demoProps?: Record<string, unknown>
}

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader()
    const exportName = Object.keys(mod).find((key) => typeof mod[key] === 'function' || typeof mod[key] === 'object')
    const Component = mod.default || (exportName ? mod[exportName] : null)

    if (!Component) {
      throw new Error('Registry module has no React component export.')
    }

    if (mod.animations) LazyComponent.animations = mod.animations
    return { default: Component }
  }) as RegistryComponent

  LazyComponent.demoProps = demoProps
  return LazyComponent
}

export const registryComponents: Record<string, RegistryComponent> = {
  'demo-primitives-p-input-1': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input/p-input-1/index.tsx'),
    {},
  ),
  'demo-primitives-p-input-10': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input/p-input-10/index.tsx'),
    {},
  ),
  'demo-primitives-p-input-11': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input/p-input-11/index.tsx'),
    {},
  ),
  'demo-primitives-p-input-12': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input/p-input-12/index.tsx'),
    {},
  ),
  'demo-primitives-p-input-13': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input/p-input-13/index.tsx'),
    {},
  ),
  'demo-primitives-p-input-14': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input/p-input-14/index.tsx'),
    {},
  ),
  'demo-primitives-p-input-15': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input/p-input-15/index.tsx'),
    {},
  ),
  'demo-primitives-p-input-16': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input/p-input-16/index.tsx'),
    {},
  ),
  'demo-primitives-p-input-17': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input/p-input-17/index.tsx'),
    {},
  ),
  'demo-primitives-p-input-18': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input/p-input-18/index.tsx'),
    {},
  ),
  'demo-primitives-p-input-2': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input/p-input-2/index.tsx'),
    {},
  ),
  'demo-primitives-p-input-3': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input/p-input-3/index.tsx'),
    {},
  ),
  'demo-primitives-p-input-4': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input/p-input-4/index.tsx'),
    {},
  ),
  'demo-primitives-p-input-5': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input/p-input-5/index.tsx'),
    {},
  ),
  'demo-primitives-p-input-6': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input/p-input-6/index.tsx'),
    {},
  ),
  'demo-primitives-p-input-7': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input/p-input-7/index.tsx'),
    {},
  ),
  'demo-primitives-p-input-8': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input/p-input-8/index.tsx'),
    {},
  ),
  'demo-primitives-p-input-9': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input/p-input-9/index.tsx'),
    {},
  ),
}
