/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-primitives-p-button-1": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-1/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-10": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-10/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-11": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-11/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-12": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-12/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-13": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-13/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-14": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-14/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-15": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-15/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-16": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-16/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-17": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-17/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-18": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-18/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-19": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-19/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-2": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-2/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-20": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-20/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-21": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-21/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-22": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-22/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-23": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-23/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-24": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-24/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-25": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-25/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-26": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-26/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-27": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-27/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-28": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-28/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-29": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-29/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-3": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-3/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-4": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-4/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-5": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-5/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-6": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-6/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-7": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-7/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-8": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-8/index.tsx"),
    {},
  ),
  "demo-primitives-p-button-9": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/button/p-button-9/index.tsx"),
    {},
  ),
};
