/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react'

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>
  demoProps?: Record<string, unknown>
}

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader()
    const exportName = Object.keys(mod).find((key) => typeof mod[key] === 'function' || typeof mod[key] === 'object')
    const Component = mod.default || (exportName ? mod[exportName] : null)

    if (!Component) {
      throw new Error('Registry module has no React component export.')
    }

    if (mod.animations) LazyComponent.animations = mod.animations
    return { default: Component }
  }) as RegistryComponent

  LazyComponent.demoProps = demoProps
  return LazyComponent
}

export const registryComponents: Record<string, RegistryComponent> = {
  'demo-primitives-p-autocomplete-1': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-1/index.tsx'),
    {},
  ),
  'demo-primitives-p-autocomplete-10': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-10/index.tsx'),
    {},
  ),
  'demo-primitives-p-autocomplete-11': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-11/index.tsx'),
    {},
  ),
  'demo-primitives-p-autocomplete-12': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-12/index.tsx'),
    {},
  ),
  'demo-primitives-p-autocomplete-13': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-13/index.tsx'),
    {},
  ),
  'demo-primitives-p-autocomplete-14': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-14/index.tsx'),
    {},
  ),
  'demo-primitives-p-autocomplete-15': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-15/index.tsx'),
    {},
  ),
  'demo-primitives-p-autocomplete-2': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-2/index.tsx'),
    {},
  ),
  'demo-primitives-p-autocomplete-3': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-3/index.tsx'),
    {},
  ),
  'demo-primitives-p-autocomplete-4': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-4/index.tsx'),
    {},
  ),
  'demo-primitives-p-autocomplete-5': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-5/index.tsx'),
    {},
  ),
  'demo-primitives-p-autocomplete-6': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-6/index.tsx'),
    {},
  ),
  'demo-primitives-p-autocomplete-7': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-7/index.tsx'),
    {},
  ),
  'demo-primitives-p-autocomplete-8': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-8/index.tsx'),
    {},
  ),
  'demo-primitives-p-autocomplete-9': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-9/index.tsx'),
    {},
  ),
}
