/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-primitives-p-otp-field-1": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/otp-field/p-otp-field-1/index.tsx"),
    {},
  ),
  "demo-primitives-p-otp-field-2": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/otp-field/p-otp-field-2/index.tsx"),
    {},
  ),
  "demo-primitives-p-otp-field-3": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/otp-field/p-otp-field-3/index.tsx"),
    {},
  ),
  "demo-primitives-p-otp-field-4": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/otp-field/p-otp-field-4/index.tsx"),
    {},
  ),
  "demo-primitives-p-otp-field-5": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/otp-field/p-otp-field-5/index.tsx"),
    {},
  ),
  "demo-primitives-p-otp-field-6": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/otp-field/p-otp-field-6/index.tsx"),
    {},
  ),
  "demo-primitives-p-otp-field-7": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/otp-field/p-otp-field-7/index.tsx"),
    {},
  ),
  "demo-primitives-p-otp-field-8": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/otp-field/p-otp-field-8/index.tsx"),
    {},
  ),
  "demo-primitives-p-otp-field-9": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/otp-field/p-otp-field-9/index.tsx"),
    {},
  ),
};
