/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react'

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>
  demoProps?: Record<string, unknown>
}

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader()
    const exportName = Object.keys(mod).find((key) => typeof mod[key] === 'function' || typeof mod[key] === 'object')
    const Component = mod.default || (exportName ? mod[exportName] : null)

    if (!Component) {
      throw new Error('Registry module has no React component export.')
    }

    if (mod.animations) LazyComponent.animations = mod.animations
    return { default: Component }
  }) as RegistryComponent

  LazyComponent.demoProps = demoProps
  return LazyComponent
}

export const registryComponents: Record<string, RegistryComponent> = {
  'demo-components-spaceui-c-filters-1': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-1/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-filters-10': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-10/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-filters-11': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-11/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-filters-12': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-12/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-filters-2': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-2/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-filters-3': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-3/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-filters-4': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-4/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-filters-5': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-5/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-filters-6': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-6/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-filters-7': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-7/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-filters-8': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-8/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-filters-9': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-9/index.tsx'),
    {},
  ),
}
