/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react'

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>
  demoProps?: Record<string, unknown>
}

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader()
    const exportName = Object.keys(mod).find((key) => typeof mod[key] === 'function' || typeof mod[key] === 'object')
    const Component = mod.default || (exportName ? mod[exportName] : null)

    if (!Component) {
      throw new Error('Registry module has no React component export.')
    }

    if (mod.animations) LazyComponent.animations = mod.animations
    return { default: Component }
  }) as RegistryComponent

  LazyComponent.demoProps = demoProps
  return LazyComponent
}

export const registryComponents: Record<string, RegistryComponent> = {
  'demo-components-spaceui-c-dirt-carousel-1': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/dirt-carousel/c-dirt-carousel-1/index.tsx'),
    {
      direction: { value: 'flat', options: { Flat: 'flat', Up: 'up', Down: 'down' } },
      radius: { value: 800, min: 300, max: 1200, step: 20 },
      ballSize: { value: 800, min: 300, max: 1200, step: 20 },
      bounce: { value: false },
      mouseTilt: { value: false },
      snap: { value: true },
      autoRotate: { value: false },
    },
  ),
}
