/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react'

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>
  demoProps?: Record<string, unknown>
}

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader()
    const exportName = Object.keys(mod).find((key) => typeof mod[key] === 'function' || typeof mod[key] === 'object')
    const Component = mod.default || (exportName ? mod[exportName] : null)

    if (!Component) {
      throw new Error('Registry module has no React component export.')
    }

    if (mod.animations) LazyComponent.animations = mod.animations
    return { default: Component }
  }) as RegistryComponent

  LazyComponent.demoProps = demoProps
  return LazyComponent
}

export const registryComponents: Record<string, RegistryComponent> = {
  'demo-primitives-p-calendar-1': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-1/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-10': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-10/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-11': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-11/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-12': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-12/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-13': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-13/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-14': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-14/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-15': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-15/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-16': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-16/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-17': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-17/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-18': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-18/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-19': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-19/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-2': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-2/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-20': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-20/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-21': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-21/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-22': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-22/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-23': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-23/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-24': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-24/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-25': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-25/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-3': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-3/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-4': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-4/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-5': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-5/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-6': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-6/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-7': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-7/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-8': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-8/index.tsx'),
    {},
  ),
  'demo-primitives-p-calendar-9': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/calendar/p-calendar-9/index.tsx'),
    {},
  ),
}
