/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react'

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>
  demoProps?: Record<string, unknown>
}

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader()
    const exportName = Object.keys(mod).find((key) => typeof mod[key] === 'function' || typeof mod[key] === 'object')
    const Component = mod.default || (exportName ? mod[exportName] : null)

    if (!Component) {
      throw new Error('Registry module has no React component export.')
    }

    if (mod.animations) LazyComponent.animations = mod.animations
    return { default: Component }
  }) as RegistryComponent

  LazyComponent.demoProps = demoProps
  return LazyComponent
}

export const registryComponents: Record<string, RegistryComponent> = {
  'demo-p-autocomplete-01': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-01/index.tsx'),
    {},
  ),
  'demo-p-autocomplete-02': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-02/index.tsx'),
    {},
  ),
  'demo-p-autocomplete-03': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-03/index.tsx'),
    {},
  ),
  'demo-p-autocomplete-04': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-04/index.tsx'),
    {},
  ),
  'demo-p-autocomplete-05': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-05/index.tsx'),
    {},
  ),
  'demo-p-autocomplete-06': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-06/index.tsx'),
    {},
  ),
  'demo-p-autocomplete-07': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-07/index.tsx'),
    {},
  ),
  'demo-p-autocomplete-08': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-08/index.tsx'),
    {},
  ),
  'demo-p-autocomplete-09': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-09/index.tsx'),
    {},
  ),
  'demo-p-autocomplete-10': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-10/index.tsx'),
    {},
  ),
  'demo-p-autocomplete-11': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-11/index.tsx'),
    {},
  ),
  'demo-p-autocomplete-12': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-12/index.tsx'),
    {},
  ),
  'demo-p-autocomplete-13': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-13/index.tsx'),
    {},
  ),
  'demo-p-autocomplete-14': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-14/index.tsx'),
    {},
  ),
  'demo-p-autocomplete-15': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/autocomplete/p-autocomplete-15/index.tsx'),
    {},
  ),
}
