/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react'

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>
  demoProps?: Record<string, unknown>
}

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader()
    const exportName = Object.keys(mod).find((key) => typeof mod[key] === 'function' || typeof mod[key] === 'object')
    const Component = mod.default || (exportName ? mod[exportName] : null)

    if (!Component) {
      throw new Error('Registry module has no React component export.')
    }

    if (mod.animations) LazyComponent.animations = mod.animations
    return { default: Component }
  }) as RegistryComponent

  LazyComponent.demoProps = demoProps
  return LazyComponent
}

export const registryComponents: Record<string, RegistryComponent> = {
  'demo-components-spaceui-c-data-grid-1': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-1/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-10': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-10/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-11': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-11/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-12': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-12/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-13': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-13/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-14': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-14/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-15': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-15/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-16': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-16/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-17': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-17/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-18': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-18/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-19': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-19/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-2': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-2/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-20': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-20/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-21': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-21/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-22': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-22/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-23': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-23/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-24': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-24/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-25': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-25/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-26': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-26/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-27': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-27/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-28': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-28/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-29': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-29/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-3': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-3/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-4': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-4/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-5': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-5/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-6': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-6/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-7': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-7/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-8': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-8/index.tsx'),
    {},
  ),
  'demo-components-spaceui-c-data-grid-9': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/data-grid/c-data-grid-9/index.tsx'),
    {},
  ),
}
