/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-p-slider-01": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-01/index.tsx"),
    {},
  ),
  "demo-p-slider-02": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-02/index.tsx"),
    {},
  ),
  "demo-p-slider-03": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-03/index.tsx"),
    {},
  ),
  "demo-p-slider-04": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-04/index.tsx"),
    {},
  ),
  "demo-p-slider-05": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-05/index.tsx"),
    {},
  ),
  "demo-p-slider-06": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-06/index.tsx"),
    {},
  ),
  "demo-p-slider-07": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-07/index.tsx"),
    {},
  ),
  "demo-p-slider-08": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-08/index.tsx"),
    {},
  ),
  "demo-p-slider-09": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-09/index.tsx"),
    {},
  ),
  "demo-p-slider-10": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-10/index.tsx"),
    {},
  ),
  "demo-p-slider-11": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-11/index.tsx"),
    {},
  ),
  "demo-p-slider-12": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-12/index.tsx"),
    {},
  ),
  "demo-p-slider-13": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-13/index.tsx"),
    {},
  ),
  "demo-p-slider-14": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-14/index.tsx"),
    {},
  ),
  "demo-p-slider-15": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-15/index.tsx"),
    {},
  ),
  "demo-p-slider-16": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-16/index.tsx"),
    {},
  ),
  "demo-p-slider-17": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-17/index.tsx"),
    {},
  ),
  "demo-p-slider-18": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-18/index.tsx"),
    {},
  ),
  "demo-p-slider-19": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-19/index.tsx"),
    {},
  ),
  "demo-p-slider-20": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-20/index.tsx"),
    {},
  ),
  "demo-p-slider-21": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-21/index.tsx"),
    {},
  ),
  "demo-p-slider-22": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-22/index.tsx"),
    {},
  ),
  "demo-p-slider-23": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/slider/p-slider-23/index.tsx"),
    {},
  ),
};
