/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-p-drawer-01": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/drawer/p-drawer-01/index.tsx"),
    {},
  ),
  "demo-p-drawer-02": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/drawer/p-drawer-02/index.tsx"),
    {},
  ),
  "demo-p-drawer-03": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/drawer/p-drawer-03/index.tsx"),
    {},
  ),
  "demo-p-drawer-04": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/drawer/p-drawer-04/index.tsx"),
    {},
  ),
  "demo-p-drawer-05": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/drawer/p-drawer-05/index.tsx"),
    {},
  ),
  "demo-p-drawer-06": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/drawer/p-drawer-06/index.tsx"),
    {},
  ),
  "demo-p-drawer-07": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/drawer/p-drawer-07/index.tsx"),
    {},
  ),
  "demo-p-drawer-08": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/drawer/p-drawer-08/index.tsx"),
    {},
  ),
  "demo-p-drawer-09": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/drawer/p-drawer-09/index.tsx"),
    {},
  ),
  "demo-p-drawer-10": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/drawer/p-drawer-10/index.tsx"),
    {},
  ),
  "demo-p-drawer-11": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/drawer/p-drawer-11/index.tsx"),
    {},
  ),
  "demo-p-drawer-12": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/drawer/p-drawer-12/index.tsx"),
    {},
  ),
  "demo-p-drawer-13": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/drawer/p-drawer-13/index.tsx"),
    {},
  ),
  "demo-p-drawer-14": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/drawer/p-drawer-14/index.tsx"),
    {},
  ),
};
