/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-primitives-p-select-1": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/select/p-select-1/index.tsx"),
    {},
  ),
  "demo-primitives-p-select-10": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/select/p-select-10/index.tsx"),
    {},
  ),
  "demo-primitives-p-select-11": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/select/p-select-11/index.tsx"),
    {},
  ),
  "demo-primitives-p-select-12": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/select/p-select-12/index.tsx"),
    {},
  ),
  "demo-primitives-p-select-13": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/select/p-select-13/index.tsx"),
    {},
  ),
  "demo-primitives-p-select-14": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/select/p-select-14/index.tsx"),
    {},
  ),
  "demo-primitives-p-select-15": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/select/p-select-15/index.tsx"),
    {},
  ),
  "demo-primitives-p-select-16": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/select/p-select-16/index.tsx"),
    {},
  ),
  "demo-primitives-p-select-17": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/select/p-select-17/index.tsx"),
    {},
  ),
  "demo-primitives-p-select-18": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/select/p-select-18/index.tsx"),
    {},
  ),
  "demo-primitives-p-select-19": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/select/p-select-19/index.tsx"),
    {},
  ),
  "demo-primitives-p-select-2": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/select/p-select-2/index.tsx"),
    {},
  ),
  "demo-primitives-p-select-20": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/select/p-select-20/index.tsx"),
    {},
  ),
  "demo-primitives-p-select-21": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/select/p-select-21/index.tsx"),
    {},
  ),
  "demo-primitives-p-select-22": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/select/p-select-22/index.tsx"),
    {},
  ),
  "demo-primitives-p-select-3": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/select/p-select-3/index.tsx"),
    {},
  ),
  "demo-primitives-p-select-4": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/select/p-select-4/index.tsx"),
    {},
  ),
  "demo-primitives-p-select-5": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/select/p-select-5/index.tsx"),
    {},
  ),
  "demo-primitives-p-select-6": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/select/p-select-6/index.tsx"),
    {},
  ),
  "demo-primitives-p-select-7": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/select/p-select-7/index.tsx"),
    {},
  ),
  "demo-primitives-p-select-8": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/select/p-select-8/index.tsx"),
    {},
  ),
  "demo-primitives-p-select-9": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/select/p-select-9/index.tsx"),
    {},
  ),
};
