/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react'

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>
  demoProps?: Record<string, unknown>
}

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader()
    const exportName = Object.keys(mod).find((key) => typeof mod[key] === 'function' || typeof mod[key] === 'object')
    const Component = mod.default || (exportName ? mod[exportName] : null)

    if (!Component) {
      throw new Error('Registry module has no React component export.')
    }

    if (mod.animations) LazyComponent.animations = mod.animations
    return { default: Component }
  }) as RegistryComponent

  LazyComponent.demoProps = demoProps
  return LazyComponent
}

export const registryComponents: Record<string, RegistryComponent> = {
  'demo-p-table-01': lazyRegistryComponent(() => import('@/registry/demo/primitives/table/p-table-01/index.tsx'), {}),
  'demo-p-table-02': lazyRegistryComponent(() => import('@/registry/demo/primitives/table/p-table-02/index.tsx'), {}),
  'demo-p-table-03': lazyRegistryComponent(() => import('@/registry/demo/primitives/table/p-table-03/index.tsx'), {}),
  'demo-p-table-04': lazyRegistryComponent(() => import('@/registry/demo/primitives/table/p-table-04/index.tsx'), {}),
  'demo-p-table-05': lazyRegistryComponent(() => import('@/registry/demo/primitives/table/p-table-05/index.tsx'), {}),
  'demo-p-table-06': lazyRegistryComponent(() => import('@/registry/demo/primitives/table/p-table-06/index.tsx'), {}),
  'demo-p-table-07': lazyRegistryComponent(() => import('@/registry/demo/primitives/table/p-table-07/index.tsx'), {}),
  'demo-p-table-08': lazyRegistryComponent(() => import('@/registry/demo/primitives/table/p-table-08/index.tsx'), {}),
  'demo-p-table-09': lazyRegistryComponent(() => import('@/registry/demo/primitives/table/p-table-09/index.tsx'), {}),
}
