/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-primitives-p-textarea-1": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/textarea/p-textarea-1/index.tsx"),
    {},
  ),
  "demo-primitives-p-textarea-10": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/textarea/p-textarea-10/index.tsx"),
    {},
  ),
  "demo-primitives-p-textarea-11": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/textarea/p-textarea-11/index.tsx"),
    {},
  ),
  "demo-primitives-p-textarea-12": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/textarea/p-textarea-12/index.tsx"),
    {},
  ),
  "demo-primitives-p-textarea-13": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/textarea/p-textarea-13/index.tsx"),
    {},
  ),
  "demo-primitives-p-textarea-14": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/textarea/p-textarea-14/index.tsx"),
    {},
  ),
  "demo-primitives-p-textarea-2": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/textarea/p-textarea-2/index.tsx"),
    {},
  ),
  "demo-primitives-p-textarea-3": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/textarea/p-textarea-3/index.tsx"),
    {},
  ),
  "demo-primitives-p-textarea-4": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/textarea/p-textarea-4/index.tsx"),
    {},
  ),
  "demo-primitives-p-textarea-5": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/textarea/p-textarea-5/index.tsx"),
    {},
  ),
  "demo-primitives-p-textarea-6": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/textarea/p-textarea-6/index.tsx"),
    {},
  ),
  "demo-primitives-p-textarea-7": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/textarea/p-textarea-7/index.tsx"),
    {},
  ),
  "demo-primitives-p-textarea-8": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/textarea/p-textarea-8/index.tsx"),
    {},
  ),
  "demo-primitives-p-textarea-9": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/textarea/p-textarea-9/index.tsx"),
    {},
  ),
};
