/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react'

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>
  demoProps?: Record<string, unknown>
}

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader()
    const exportName = Object.keys(mod).find((key) => typeof mod[key] === 'function' || typeof mod[key] === 'object')
    const Component = mod.default || (exportName ? mod[exportName] : null)

    if (!Component) {
      throw new Error('Registry module has no React component export.')
    }

    if (mod.animations) LazyComponent.animations = mod.animations
    return { default: Component }
  }) as RegistryComponent

  LazyComponent.demoProps = demoProps
  return LazyComponent
}

export const registryComponents: Record<string, RegistryComponent> = {
  'demo-c-filters-01': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-01/index.tsx'),
    {},
  ),
  'demo-c-filters-02': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-02/index.tsx'),
    {},
  ),
  'demo-c-filters-03': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-03/index.tsx'),
    {},
  ),
  'demo-c-filters-04': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-04/index.tsx'),
    {},
  ),
  'demo-c-filters-05': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-05/index.tsx'),
    {},
  ),
  'demo-c-filters-06': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-06/index.tsx'),
    {},
  ),
  'demo-c-filters-07': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-07/index.tsx'),
    {},
  ),
  'demo-c-filters-08': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-08/index.tsx'),
    {},
  ),
  'demo-c-filters-09': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-09/index.tsx'),
    {},
  ),
  'demo-c-filters-10': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-10/index.tsx'),
    {},
  ),
  'demo-c-filters-11': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-11/index.tsx'),
    {},
  ),
  'demo-c-filters-12': lazyRegistryComponent(
    () => import('@/registry/demo/components/spaceui/filters/c-filters-12/index.tsx'),
    {},
  ),
}
