/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react'

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>
  demoProps?: Record<string, unknown>
}

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader()
    const exportName = Object.keys(mod).find((key) => typeof mod[key] === 'function' || typeof mod[key] === 'object')
    const Component = mod.default || (exportName ? mod[exportName] : null)

    if (!Component) {
      throw new Error('Registry module has no React component export.')
    }

    if (mod.animations) LazyComponent.animations = mod.animations
    return { default: Component }
  }) as RegistryComponent

  LazyComponent.demoProps = demoProps
  return LazyComponent
}

export const registryComponents: Record<string, RegistryComponent> = {
  'demo-c-cloud-01': lazyRegistryComponent(
    () => import('@/registry/demo/components/shader/cloud/c-cloud-01/index.tsx'),
    {
      speed: { value: 1, min: 0, max: 5, step: 0.1 },
      sky: { value: '#68b8d7' },
      cloudColor: { value: '#adc1de' },
      shadow: { value: '#183550' },
      sun: { value: '#ff9919' },
      glare: { value: '#ff6633' },
      sunlight: { value: '#ff9933' },
      bg: { value: '#ffffff' },
    },
  ),
}
