/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-c-rating-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/rating/c-rating-01/index.tsx"),
    {},
  ),
  "demo-c-rating-02": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/rating/c-rating-02/index.tsx"),
    {},
  ),
  "demo-c-rating-03": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/rating/c-rating-03/index.tsx"),
    {},
  ),
  "demo-c-rating-04": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/rating/c-rating-04/index.tsx"),
    {},
  ),
  "demo-c-rating-05": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/rating/c-rating-05/index.tsx"),
    {},
  ),
  "demo-c-rating-06": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/rating/c-rating-06/index.tsx"),
    {},
  ),
  "demo-c-rating-07": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/rating/c-rating-07/index.tsx"),
    {},
  ),
  "demo-c-rating-08": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/rating/c-rating-08/index.tsx"),
    {},
  ),
  "demo-c-rating-09": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/rating/c-rating-09/index.tsx"),
    {},
  ),
};
