/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react'

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>
  demoProps?: Record<string, unknown>
}

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader()
    const exportName = Object.keys(mod).find((key) => typeof mod[key] === 'function' || typeof mod[key] === 'object')
    const Component = mod.default || (exportName ? mod[exportName] : null)

    if (!Component) {
      throw new Error('Registry module has no React component export.')
    }

    if (mod.animations) LazyComponent.animations = mod.animations
    return { default: Component }
  }) as RegistryComponent

  LazyComponent.demoProps = demoProps
  return LazyComponent
}

export const registryComponents: Record<string, RegistryComponent> = {
  'demo-p-field-01': lazyRegistryComponent(() => import('@/registry/demo/primitives/field/p-field-01/index.tsx'), {}),
  'demo-p-field-02': lazyRegistryComponent(() => import('@/registry/demo/primitives/field/p-field-02/index.tsx'), {}),
  'demo-p-field-03': lazyRegistryComponent(() => import('@/registry/demo/primitives/field/p-field-03/index.tsx'), {}),
  'demo-p-field-04': lazyRegistryComponent(() => import('@/registry/demo/primitives/field/p-field-04/index.tsx'), {}),
  'demo-p-field-05': lazyRegistryComponent(() => import('@/registry/demo/primitives/field/p-field-05/index.tsx'), {}),
  'demo-p-field-06': lazyRegistryComponent(() => import('@/registry/demo/primitives/field/p-field-06/index.tsx'), {}),
  'demo-p-field-07': lazyRegistryComponent(() => import('@/registry/demo/primitives/field/p-field-07/index.tsx'), {}),
  'demo-p-field-08': lazyRegistryComponent(() => import('@/registry/demo/primitives/field/p-field-08/index.tsx'), {}),
  'demo-p-field-09': lazyRegistryComponent(() => import('@/registry/demo/primitives/field/p-field-09/index.tsx'), {}),
  'demo-p-field-10': lazyRegistryComponent(() => import('@/registry/demo/primitives/field/p-field-10/index.tsx'), {}),
  'demo-p-field-11': lazyRegistryComponent(() => import('@/registry/demo/primitives/field/p-field-11/index.tsx'), {}),
  'demo-p-field-12': lazyRegistryComponent(() => import('@/registry/demo/primitives/field/p-field-12/index.tsx'), {}),
  'demo-p-field-13': lazyRegistryComponent(() => import('@/registry/demo/primitives/field/p-field-13/index.tsx'), {}),
  'demo-p-field-14': lazyRegistryComponent(() => import('@/registry/demo/primitives/field/p-field-14/index.tsx'), {}),
  'demo-p-field-15': lazyRegistryComponent(() => import('@/registry/demo/primitives/field/p-field-15/index.tsx'), {}),
  'demo-p-field-16': lazyRegistryComponent(() => import('@/registry/demo/primitives/field/p-field-16/index.tsx'), {}),
  'demo-p-field-17': lazyRegistryComponent(() => import('@/registry/demo/primitives/field/p-field-17/index.tsx'), {}),
  'demo-p-field-18': lazyRegistryComponent(() => import('@/registry/demo/primitives/field/p-field-18/index.tsx'), {}),
}
