/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react'

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>
  demoProps?: Record<string, unknown>
}

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader()
    const exportName = Object.keys(mod).find((key) => typeof mod[key] === 'function' || typeof mod[key] === 'object')
    const Component = mod.default || (exportName ? mod[exportName] : null)

    if (!Component) {
      throw new Error('Registry module has no React component export.')
    }

    if (mod.animations) LazyComponent.animations = mod.animations
    return { default: Component }
  }) as RegistryComponent

  LazyComponent.demoProps = demoProps
  return LazyComponent
}

export const registryComponents: Record<string, RegistryComponent> = {
  'demo-p-input-group-01': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-01/index.tsx'),
    {},
  ),
  'demo-p-input-group-02': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-02/index.tsx'),
    {},
  ),
  'demo-p-input-group-03': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-03/index.tsx'),
    {},
  ),
  'demo-p-input-group-04': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-04/index.tsx'),
    {},
  ),
  'demo-p-input-group-05': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-05/index.tsx'),
    {},
  ),
  'demo-p-input-group-06': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-06/index.tsx'),
    {},
  ),
  'demo-p-input-group-07': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-07/index.tsx'),
    {},
  ),
  'demo-p-input-group-08': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-08/index.tsx'),
    {},
  ),
  'demo-p-input-group-09': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-09/index.tsx'),
    {},
  ),
  'demo-p-input-group-10': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-10/index.tsx'),
    {},
  ),
  'demo-p-input-group-11': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-11/index.tsx'),
    {},
  ),
  'demo-p-input-group-12': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-12/index.tsx'),
    {},
  ),
  'demo-p-input-group-13': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-13/index.tsx'),
    {},
  ),
  'demo-p-input-group-14': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-14/index.tsx'),
    {},
  ),
  'demo-p-input-group-15': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-15/index.tsx'),
    {},
  ),
  'demo-p-input-group-16': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-16/index.tsx'),
    {},
  ),
  'demo-p-input-group-17': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-17/index.tsx'),
    {},
  ),
  'demo-p-input-group-18': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-18/index.tsx'),
    {},
  ),
  'demo-p-input-group-19': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-19/index.tsx'),
    {},
  ),
  'demo-p-input-group-20': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-20/index.tsx'),
    {},
  ),
  'demo-p-input-group-21': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-21/index.tsx'),
    {},
  ),
  'demo-p-input-group-22': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-22/index.tsx'),
    {},
  ),
  'demo-p-input-group-23': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-23/index.tsx'),
    {},
  ),
  'demo-p-input-group-24': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-24/index.tsx'),
    {},
  ),
  'demo-p-input-group-25': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-25/index.tsx'),
    {},
  ),
  'demo-p-input-group-26': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-26/index.tsx'),
    {},
  ),
  'demo-p-input-group-27': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-27/index.tsx'),
    {},
  ),
  'demo-p-input-group-28': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/input-group/p-input-group-28/index.tsx'),
    {},
  ),
}
