/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react'

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>
  demoProps?: Record<string, unknown>
}

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader()
    const exportName = Object.keys(mod).find((key) => typeof mod[key] === 'function' || typeof mod[key] === 'object')
    const Component = mod.default || (exportName ? mod[exportName] : null)

    if (!Component) {
      throw new Error('Registry module has no React component export.')
    }

    if (mod.animations) LazyComponent.animations = mod.animations
    return { default: Component }
  }) as RegistryComponent

  LazyComponent.demoProps = demoProps
  return LazyComponent
}

export const registryComponents: Record<string, RegistryComponent> = {
  'demo-p-textarea-01': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/textarea/p-textarea-01/index.tsx'),
    {},
  ),
  'demo-p-textarea-02': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/textarea/p-textarea-02/index.tsx'),
    {},
  ),
  'demo-p-textarea-03': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/textarea/p-textarea-03/index.tsx'),
    {},
  ),
  'demo-p-textarea-04': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/textarea/p-textarea-04/index.tsx'),
    {},
  ),
  'demo-p-textarea-05': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/textarea/p-textarea-05/index.tsx'),
    {},
  ),
  'demo-p-textarea-06': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/textarea/p-textarea-06/index.tsx'),
    {},
  ),
  'demo-p-textarea-07': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/textarea/p-textarea-07/index.tsx'),
    {},
  ),
  'demo-p-textarea-08': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/textarea/p-textarea-08/index.tsx'),
    {},
  ),
  'demo-p-textarea-09': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/textarea/p-textarea-09/index.tsx'),
    {},
  ),
  'demo-p-textarea-10': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/textarea/p-textarea-10/index.tsx'),
    {},
  ),
  'demo-p-textarea-11': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/textarea/p-textarea-11/index.tsx'),
    {},
  ),
  'demo-p-textarea-12': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/textarea/p-textarea-12/index.tsx'),
    {},
  ),
  'demo-p-textarea-13': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/textarea/p-textarea-13/index.tsx'),
    {},
  ),
  'demo-p-textarea-14': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/textarea/p-textarea-14/index.tsx'),
    {},
  ),
}
