/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-c-theme-toggle-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/theme-toggle/c-theme-toggle-01/index.tsx"),
    {"variant":{"value":"circle","options":{"Circle":"circle","Circle Blur":"circle-blur","Rectangle":"rectangle","Polygon":"polygon"}},"startCircle":{"value":"center","label":"Direction","options":{"Center":"center","Top Left":"top-left","Top Right":"top-right","Bottom Left":"bottom-left","Bottom Right":"bottom-right","Top Center":"top-center","Bottom Center":"bottom-center"},"dependsOn":{"variant":["circle","circle-blur"]}},"startRectangle":{"value":"bottom-up","label":"Direction","options":{"Bottom Up":"bottom-up","Top Down":"top-down","Left Right":"left-right","Right Left":"right-left","Top Left":"top-left","Top Right":"top-right","Bottom Left":"bottom-left","Bottom Right":"bottom-right"},"dependsOn":{"variant":"rectangle"}},"startPolygon":{"value":"top-left","label":"Direction","options":{"Top Left":"top-left","Top Right":"top-right"},"dependsOn":{"variant":"polygon"}},"blur":{"value":false,"dependsOn":{"variant":["circle","rectangle","polygon"]}},"buttonVariant":{"value":"outline","options":{"Outline":"outline","Secondary":"secondary","Default":"default","Ghost":"ghost"}},"size":{"value":"lg","options":{"XS":"xs","SM":"sm","MD":"md","LG":"lg","XL":"xl"}}},
  ),
};
