/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-c-liquid-metal-avatar-custom-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/c-liquid-metal-avatar-custom-01/index.tsx"),
    {},
  ),
  "demo-c-liquid-metal-avatar-default-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/c-liquid-metal-avatar-default-01/index.tsx"),
    {},
  ),
  "demo-c-liquid-metal-avatar-fallback-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/c-liquid-metal-avatar-fallback-01/index.tsx"),
    {},
  ),
  "demo-c-liquid-metal-avatar-sizes-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/c-liquid-metal-avatar-sizes-01/index.tsx"),
    {},
  ),
  "demo-c-liquid-metal-button-custom-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/c-liquid-metal-button-custom-01/index.tsx"),
    {},
  ),
  "demo-c-liquid-metal-button-default-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/c-liquid-metal-button-default-01/index.tsx"),
    {},
  ),
  "demo-c-liquid-metal-button-sizes-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/c-liquid-metal-button-sizes-01/index.tsx"),
    {},
  ),
  "demo-c-liquid-metal-card-custom-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/c-liquid-metal-card-custom-01/index.tsx"),
    {},
  ),
  "demo-c-liquid-metal-card-default-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/c-liquid-metal-card-default-01/index.tsx"),
    {},
  ),
  "demo-c-liquid-metal-card-login-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/c-liquid-metal-card-login-01/index.tsx"),
    {},
  ),
  "demo-c-liquid-metal-card-player-01": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/c-liquid-metal-card-player-01/index.tsx"),
    {},
  ),
};
