/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "demo-primitives-p-combobox-1": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/combobox/p-combobox-1/index.tsx"),
    {},
  ),
  "demo-primitives-p-combobox-10": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/combobox/p-combobox-10/index.tsx"),
    {},
  ),
  "demo-primitives-p-combobox-11": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/combobox/p-combobox-11/index.tsx"),
    {},
  ),
  "demo-primitives-p-combobox-12": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/combobox/p-combobox-12/index.tsx"),
    {},
  ),
  "demo-primitives-p-combobox-13": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/combobox/p-combobox-13/index.tsx"),
    {},
  ),
  "demo-primitives-p-combobox-14": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/combobox/p-combobox-14/index.tsx"),
    {},
  ),
  "demo-primitives-p-combobox-15": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/combobox/p-combobox-15/index.tsx"),
    {},
  ),
  "demo-primitives-p-combobox-16": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/combobox/p-combobox-16/index.tsx"),
    {},
  ),
  "demo-primitives-p-combobox-17": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/combobox/p-combobox-17/index.tsx"),
    {},
  ),
  "demo-primitives-p-combobox-18": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/combobox/p-combobox-18/index.tsx"),
    {},
  ),
  "demo-primitives-p-combobox-19": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/combobox/p-combobox-19/index.tsx"),
    {},
  ),
  "demo-primitives-p-combobox-2": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/combobox/p-combobox-2/index.tsx"),
    {},
  ),
  "demo-primitives-p-combobox-3": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/combobox/p-combobox-3/index.tsx"),
    {},
  ),
  "demo-primitives-p-combobox-4": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/combobox/p-combobox-4/index.tsx"),
    {},
  ),
  "demo-primitives-p-combobox-5": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/combobox/p-combobox-5/index.tsx"),
    {},
  ),
  "demo-primitives-p-combobox-6": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/combobox/p-combobox-6/index.tsx"),
    {},
  ),
  "demo-primitives-p-combobox-7": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/combobox/p-combobox-7/index.tsx"),
    {},
  ),
  "demo-primitives-p-combobox-8": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/combobox/p-combobox-8/index.tsx"),
    {},
  ),
  "demo-primitives-p-combobox-9": lazyRegistryComponent(
    () => import("@/registry/demo/primitives/combobox/p-combobox-9/index.tsx"),
    {},
  ),
};
