/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react'

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>
  demoProps?: Record<string, unknown>
}

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader()
    const exportName = Object.keys(mod).find((key) => typeof mod[key] === 'function' || typeof mod[key] === 'object')
    const Component = mod.default || (exportName ? mod[exportName] : null)

    if (!Component) {
      throw new Error('Registry module has no React component export.')
    }

    if (mod.animations) LazyComponent.animations = mod.animations
    return { default: Component }
  }) as RegistryComponent

  LazyComponent.demoProps = demoProps
  return LazyComponent
}

export const registryComponents: Record<string, RegistryComponent> = {
  'demo-p-select-01': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/select/p-select-01/index.tsx'),
    {},
  ),
  'demo-p-select-02': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/select/p-select-02/index.tsx'),
    {},
  ),
  'demo-p-select-03': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/select/p-select-03/index.tsx'),
    {},
  ),
  'demo-p-select-04': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/select/p-select-04/index.tsx'),
    {},
  ),
  'demo-p-select-05': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/select/p-select-05/index.tsx'),
    {},
  ),
  'demo-p-select-06': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/select/p-select-06/index.tsx'),
    {},
  ),
  'demo-p-select-07': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/select/p-select-07/index.tsx'),
    {},
  ),
  'demo-p-select-08': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/select/p-select-08/index.tsx'),
    {},
  ),
  'demo-p-select-09': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/select/p-select-09/index.tsx'),
    {},
  ),
  'demo-p-select-10': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/select/p-select-10/index.tsx'),
    {},
  ),
  'demo-p-select-11': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/select/p-select-11/index.tsx'),
    {},
  ),
  'demo-p-select-12': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/select/p-select-12/index.tsx'),
    {},
  ),
  'demo-p-select-13': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/select/p-select-13/index.tsx'),
    {},
  ),
  'demo-p-select-14': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/select/p-select-14/index.tsx'),
    {},
  ),
  'demo-p-select-15': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/select/p-select-15/index.tsx'),
    {},
  ),
  'demo-p-select-16': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/select/p-select-16/index.tsx'),
    {},
  ),
  'demo-p-select-17': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/select/p-select-17/index.tsx'),
    {},
  ),
  'demo-p-select-18': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/select/p-select-18/index.tsx'),
    {},
  ),
  'demo-p-select-19': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/select/p-select-19/index.tsx'),
    {},
  ),
  'demo-p-select-20': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/select/p-select-20/index.tsx'),
    {},
  ),
  'demo-p-select-21': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/select/p-select-21/index.tsx'),
    {},
  ),
  'demo-p-select-22': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/select/p-select-22/index.tsx'),
    {},
  ),
}
