/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react'

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>
  demoProps?: Record<string, unknown>
}

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader()
    const exportName = Object.keys(mod).find((key) => typeof mod[key] === 'function' || typeof mod[key] === 'object')
    const Component = mod.default || (exportName ? mod[exportName] : null)

    if (!Component) {
      throw new Error('Registry module has no React component export.')
    }

    if (mod.animations) LazyComponent.animations = mod.animations
    return { default: Component }
  }) as RegistryComponent

  LazyComponent.demoProps = demoProps
  return LazyComponent
}

export const registryComponents: Record<string, RegistryComponent> = {
  'demo-primitives-p-command-1': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/command/p-command-1/index.tsx'),
    {},
  ),
  'demo-primitives-p-command-2': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/command/p-command-2/index.tsx'),
    {},
  ),
}
