/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react'

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>
  demoProps?: Record<string, unknown>
}

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader()
    const exportName = Object.keys(mod).find((key) => typeof mod[key] === 'function' || typeof mod[key] === 'object')
    const Component = mod.default || (exportName ? mod[exportName] : null)

    if (!Component) {
      throw new Error('Registry module has no React component export.')
    }

    if (mod.animations) LazyComponent.animations = mod.animations
    return { default: Component }
  }) as RegistryComponent

  LazyComponent.demoProps = demoProps
  return LazyComponent
}

export const registryComponents: Record<string, RegistryComponent> = {
  'demo-p-button-01': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-01/index.tsx'),
    {},
  ),
  'demo-p-button-02': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-02/index.tsx'),
    {},
  ),
  'demo-p-button-03': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-03/index.tsx'),
    {},
  ),
  'demo-p-button-04': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-04/index.tsx'),
    {},
  ),
  'demo-p-button-05': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-05/index.tsx'),
    {},
  ),
  'demo-p-button-06': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-06/index.tsx'),
    {},
  ),
  'demo-p-button-07': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-07/index.tsx'),
    {},
  ),
  'demo-p-button-08': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-08/index.tsx'),
    {},
  ),
  'demo-p-button-09': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-09/index.tsx'),
    {},
  ),
  'demo-p-button-10': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-10/index.tsx'),
    {},
  ),
  'demo-p-button-11': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-11/index.tsx'),
    {},
  ),
  'demo-p-button-12': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-12/index.tsx'),
    {},
  ),
  'demo-p-button-13': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-13/index.tsx'),
    {},
  ),
  'demo-p-button-14': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-14/index.tsx'),
    {},
  ),
  'demo-p-button-15': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-15/index.tsx'),
    {},
  ),
  'demo-p-button-16': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-16/index.tsx'),
    {},
  ),
  'demo-p-button-17': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-17/index.tsx'),
    {},
  ),
  'demo-p-button-18': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-18/index.tsx'),
    {},
  ),
  'demo-p-button-19': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-19/index.tsx'),
    {},
  ),
  'demo-p-button-20': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-20/index.tsx'),
    {},
  ),
  'demo-p-button-21': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-21/index.tsx'),
    {},
  ),
  'demo-p-button-22': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-22/index.tsx'),
    {},
  ),
  'demo-p-button-23': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-23/index.tsx'),
    {},
  ),
  'demo-p-button-24': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-24/index.tsx'),
    {},
  ),
  'demo-p-button-25': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-25/index.tsx'),
    {},
  ),
  'demo-p-button-26': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-26/index.tsx'),
    {},
  ),
  'demo-p-button-27': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-27/index.tsx'),
    {},
  ),
  'demo-p-button-28': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-28/index.tsx'),
    {},
  ),
  'demo-p-button-29': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/button/p-button-29/index.tsx'),
    {},
  ),
}
