/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react'

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>
  demoProps?: Record<string, unknown>
}

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader()
    const exportName = Object.keys(mod).find((key) => typeof mod[key] === 'function' || typeof mod[key] === 'object')
    const Component = mod.default || (exportName ? mod[exportName] : null)

    if (!Component) {
      throw new Error('Registry module has no React component export.')
    }

    if (mod.animations) LazyComponent.animations = mod.animations
    return { default: Component }
  }) as RegistryComponent

  LazyComponent.demoProps = demoProps
  return LazyComponent
}

export const registryComponents: Record<string, RegistryComponent> = {
  'demo-p-number-field-01': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/number-field/p-number-field-01/index.tsx'),
    {},
  ),
  'demo-p-number-field-02': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/number-field/p-number-field-02/index.tsx'),
    {},
  ),
  'demo-p-number-field-03': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/number-field/p-number-field-03/index.tsx'),
    {},
  ),
  'demo-p-number-field-04': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/number-field/p-number-field-04/index.tsx'),
    {},
  ),
  'demo-p-number-field-05': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/number-field/p-number-field-05/index.tsx'),
    {},
  ),
  'demo-p-number-field-06': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/number-field/p-number-field-06/index.tsx'),
    {},
  ),
  'demo-p-number-field-07': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/number-field/p-number-field-07/index.tsx'),
    {},
  ),
  'demo-p-number-field-08': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/number-field/p-number-field-08/index.tsx'),
    {},
  ),
  'demo-p-number-field-09': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/number-field/p-number-field-09/index.tsx'),
    {},
  ),
  'demo-p-number-field-10': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/number-field/p-number-field-10/index.tsx'),
    {},
  ),
  'demo-p-number-field-11': lazyRegistryComponent(
    () => import('@/registry/demo/primitives/number-field/p-number-field-11/index.tsx'),
    {},
  ),
}
