/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "liquid-metal-avatar-custom": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/liquid-metal-avatar-custom/index.tsx"),
    {},
  ),
  "liquid-metal-avatar-default": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/liquid-metal-avatar-default/index.tsx"),
    {},
  ),
  "liquid-metal-avatar-fallback": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/liquid-metal-avatar-fallback/index.tsx"),
    {},
  ),
  "liquid-metal-avatar-sizes": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/liquid-metal-avatar-sizes/index.tsx"),
    {},
  ),
  "liquid-metal-button-custom": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/liquid-metal-button-custom/index.tsx"),
    {},
  ),
  "liquid-metal-button-default": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/liquid-metal-button-default/index.tsx"),
    {},
  ),
  "liquid-metal-button-sizes": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/liquid-metal-button-sizes/index.tsx"),
    {},
  ),
  "liquid-metal-card-custom": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/liquid-metal-card-custom/index.tsx"),
    {},
  ),
  "liquid-metal-card-default": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/liquid-metal-card-default/index.tsx"),
    {},
  ),
  "liquid-metal-card-login": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/liquid-metal-card-login/index.tsx"),
    {},
  ),
  "liquid-metal-card-player": lazyRegistryComponent(
    () => import("@/registry/demo/components/spaceui/liquid-metal-card-player/index.tsx"),
    {},
  ),
};
