/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react'

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>
  demoProps?: Record<string, unknown>
}

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader()
    const exportName = Object.keys(mod).find((key) => typeof mod[key] === 'function' || typeof mod[key] === 'object')
    const Component = mod.default || (exportName ? mod[exportName] : null)

    if (!Component) {
      throw new Error('Registry module has no React component export.')
    }

    if (mod.animations) LazyComponent.animations = mod.animations
    return { default: Component }
  }) as RegistryComponent

  LazyComponent.demoProps = demoProps
  return LazyComponent
}

export const registryComponents: Record<string, RegistryComponent> = {
  'hooks-animation-use-auto-height': lazyRegistryComponent(
    () => import('@/registry/hooks/animation/use-auto-height/index.ts'),
    {},
  ),
  'hooks-animation-use-controlled-state': lazyRegistryComponent(
    () => import('@/registry/hooks/animation/use-controlled-state/index.ts'),
    {},
  ),
  'hooks-animation-use-data-state': lazyRegistryComponent(
    () => import('@/registry/hooks/animation/use-data-state/index.ts'),
    {},
  ),
  'hooks-animation-use-in-view': lazyRegistryComponent(
    () => import('@/registry/hooks/animation/use-in-view/index.ts'),
    {},
  ),
  'hooks-animation-use-motion-value-state': lazyRegistryComponent(
    () => import('@/registry/hooks/animation/use-motion-value-state/index.ts'),
    {},
  ),
}
