/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react'

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>
  demoProps?: Record<string, unknown>
}

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader()
    const exportName = Object.keys(mod).find((key) => typeof mod[key] === 'function' || typeof mod[key] === 'object')
    const Component = mod.default || (exportName ? mod[exportName] : null)

    if (!Component) {
      throw new Error('Registry module has no React component export.')
    }

    if (mod.animations) LazyComponent.animations = mod.animations
    return { default: Component }
  }) as RegistryComponent

  LazyComponent.demoProps = demoProps
  return LazyComponent
}

export const registryComponents: Record<string, RegistryComponent> = {
  'hooks-form-use-character-limit': lazyRegistryComponent(
    () => import('@/registry/hooks/form/use-character-limit/index.ts'),
    {},
  ),
  'hooks-form-use-file-upload': lazyRegistryComponent(
    () => import('@/registry/hooks/form/use-file-upload/index.ts'),
    {},
  ),
  'hooks-form-use-input-value': lazyRegistryComponent(
    () => import('@/registry/hooks/form/use-input-value/index.ts'),
    {},
  ),
  'hooks-form-use-load-more': lazyRegistryComponent(() => import('@/registry/hooks/form/use-load-more/index.ts'), {}),
  'hooks-form-use-map': lazyRegistryComponent(() => import('@/registry/hooks/form/use-map/index.ts'), {}),
  'hooks-form-use-mutation': lazyRegistryComponent(() => import('@/registry/hooks/form/use-mutation/index.ts'), {}),
  'hooks-form-use-pagination': lazyRegistryComponent(() => import('@/registry/hooks/form/use-pagination/index.ts'), {}),
  'hooks-form-use-parse-markdown': lazyRegistryComponent(
    () => import('@/registry/hooks/form/use-parse-markdown/index.ts'),
    {},
  ),
  'hooks-form-use-reading-time': lazyRegistryComponent(
    () => import('@/registry/hooks/form/use-reading-time/index.ts'),
    {},
  ),
  'hooks-form-use-sanitize-content': lazyRegistryComponent(
    () => import('@/registry/hooks/form/use-sanitize-content/index.ts'),
    {},
  ),
}
