/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react'

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>
  demoProps?: Record<string, unknown>
}

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader()
    const exportName = Object.keys(mod).find((key) => typeof mod[key] === 'function' || typeof mod[key] === 'object')
    const Component = mod.default || (exportName ? mod[exportName] : null)

    if (!Component) {
      throw new Error('Registry module has no React component export.')
    }

    if (mod.animations) LazyComponent.animations = mod.animations
    return { default: Component }
  }) as RegistryComponent

  LazyComponent.demoProps = demoProps
  return LazyComponent
}

export const registryComponents: Record<string, RegistryComponent> = {
  'hooks-browser-use-battery-status': lazyRegistryComponent(
    () => import('@/registry/hooks/browser/use-battery-status/index.ts'),
    {},
  ),
  'hooks-browser-use-clipboard': lazyRegistryComponent(
    () => import('@/registry/hooks/browser/use-clipboard/index.ts'),
    {},
  ),
  'hooks-browser-use-cookie': lazyRegistryComponent(() => import('@/registry/hooks/browser/use-cookie/index.ts'), {}),
  'hooks-browser-use-cookie-listener': lazyRegistryComponent(
    () => import('@/registry/hooks/browser/use-cookie-listener/index.ts'),
    {},
  ),
  'hooks-browser-use-device-os': lazyRegistryComponent(
    () => import('@/registry/hooks/browser/use-device-os/index.ts'),
    {},
  ),
  'hooks-browser-use-favicon': lazyRegistryComponent(() => import('@/registry/hooks/browser/use-favicon/index.ts'), {}),
  'hooks-browser-use-fullscreen': lazyRegistryComponent(
    () => import('@/registry/hooks/browser/use-fullscreen/index.ts'),
    {},
  ),
  'hooks-browser-use-is-mac': lazyRegistryComponent(() => import('@/registry/hooks/browser/use-is-mac/index.ts'), {}),
  'hooks-browser-use-local-storage': lazyRegistryComponent(
    () => import('@/registry/hooks/browser/use-local-storage/index.ts'),
    {},
  ),
  'hooks-browser-use-media-query': lazyRegistryComponent(
    () => import('@/registry/hooks/browser/use-media-query/index.ts'),
    {},
  ),
  'hooks-browser-use-network': lazyRegistryComponent(() => import('@/registry/hooks/browser/use-network/index.ts'), {}),
  'hooks-browser-use-orientation': lazyRegistryComponent(
    () => import('@/registry/hooks/browser/use-orientation/index.ts'),
    {},
  ),
  'hooks-browser-use-prefers-theme': lazyRegistryComponent(
    () => import('@/registry/hooks/browser/use-prefers-theme/index.ts'),
    {},
  ),
  'hooks-browser-use-script': lazyRegistryComponent(() => import('@/registry/hooks/browser/use-script/index.ts'), {}),
  'hooks-browser-use-session-storage': lazyRegistryComponent(
    () => import('@/registry/hooks/browser/use-session-storage/index.ts'),
    {},
  ),
  'hooks-browser-use-share': lazyRegistryComponent(() => import('@/registry/hooks/browser/use-share/index.ts'), {}),
  'hooks-browser-use-tab-notification': lazyRegistryComponent(
    () => import('@/registry/hooks/browser/use-tab-notification/index.ts'),
    {},
  ),
  'hooks-browser-use-title': lazyRegistryComponent(() => import('@/registry/hooks/browser/use-title/index.ts'), {}),
}
