/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "hooks-dom-use-click-outside": lazyRegistryComponent(
    () => import("@/registry/hooks/dom/use-click-outside/index.ts"),
    {},
  ),
  "hooks-dom-use-event-listener": lazyRegistryComponent(
    () => import("@/registry/hooks/dom/use-event-listener/index.ts"),
    {},
  ),
  "hooks-dom-use-hover": lazyRegistryComponent(
    () => import("@/registry/hooks/dom/use-hover/index.ts"),
    {},
  ),
  "hooks-dom-use-intersection-observer": lazyRegistryComponent(
    () => import("@/registry/hooks/dom/use-intersection-observer/index.ts"),
    {},
  ),
  "hooks-dom-use-key-press": lazyRegistryComponent(
    () => import("@/registry/hooks/dom/use-key-press/index.ts"),
    {},
  ),
  "hooks-dom-use-lock-body-scroll": lazyRegistryComponent(
    () => import("@/registry/hooks/dom/use-lock-body-scroll/index.ts"),
    {},
  ),
  "hooks-dom-use-mouse-position": lazyRegistryComponent(
    () => import("@/registry/hooks/dom/use-mouse-position/index.ts"),
    {},
  ),
  "hooks-dom-use-scroll-device": lazyRegistryComponent(
    () => import("@/registry/hooks/dom/use-scroll-device/index.ts"),
    {},
  ),
  "hooks-dom-use-scroll-position": lazyRegistryComponent(
    () => import("@/registry/hooks/dom/use-scroll-position/index.ts"),
    {},
  ),
  "hooks-dom-use-scroll-to": lazyRegistryComponent(
    () => import("@/registry/hooks/dom/use-scroll-to/index.ts"),
    {},
  ),
  "hooks-dom-use-size": lazyRegistryComponent(
    () => import("@/registry/hooks/dom/use-size/index.ts"),
    {},
  ),
  "hooks-dom-use-window-size": lazyRegistryComponent(
    () => import("@/registry/hooks/dom/use-window-size/index.ts"),
    {},
  ),
};
