/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "hooks-components-class": lazyRegistryComponent(
    () => import("@/registry/hooks/components/class/index.tsx"),
    {},
  ),
  "hooks-components-for": lazyRegistryComponent(
    () => import("@/registry/hooks/components/for/index.tsx"),
    {},
  ),
  "hooks-components-if": lazyRegistryComponent(
    () => import("@/registry/hooks/components/if/index.tsx"),
    {},
  ),
  "hooks-components-image": lazyRegistryComponent(
    () => import("@/registry/hooks/components/image/index.tsx"),
    {},
  ),
  "hooks-components-in-view": lazyRegistryComponent(
    () => import("@/registry/hooks/components/in-view/index.tsx"),
    {},
  ),
  "hooks-components-render-after": lazyRegistryComponent(
    () => import("@/registry/hooks/components/render-after/index.tsx"),
    {},
  ),
  "hooks-components-show": lazyRegistryComponent(
    () => import("@/registry/hooks/components/show/index.tsx"),
    {},
  ),
  "hooks-components-switch": lazyRegistryComponent(
    () => import("@/registry/hooks/components/switch/index.tsx"),
    {},
  ),
};
