/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react'

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>
  demoProps?: Record<string, unknown>
}

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader()
    const exportName = Object.keys(mod).find((key) => typeof mod[key] === 'function' || typeof mod[key] === 'object')
    const Component = mod.default || (exportName ? mod[exportName] : null)

    if (!Component) {
      throw new Error('Registry module has no React component export.')
    }

    if (mod.animations) LazyComponent.animations = mod.animations
    return { default: Component }
  }) as RegistryComponent

  LazyComponent.demoProps = demoProps
  return LazyComponent
}

export const registryComponents: Record<string, RegistryComponent> = {
  'hooks-lifecycle-use-confirm-exit': lazyRegistryComponent(
    () => import('@/registry/hooks/lifecycle/use-confirm-exit/index.ts'),
    {},
  ),
  'hooks-lifecycle-use-debounce': lazyRegistryComponent(
    () => import('@/registry/hooks/lifecycle/use-debounce/index.ts'),
    {},
  ),
  'hooks-lifecycle-use-event-callback': lazyRegistryComponent(
    () => import('@/registry/hooks/lifecycle/use-event-callback/index.ts'),
    {},
  ),
  'hooks-lifecycle-use-first-render': lazyRegistryComponent(
    () => import('@/registry/hooks/lifecycle/use-first-render/index.ts'),
    {},
  ),
  'hooks-lifecycle-use-first-visit': lazyRegistryComponent(
    () => import('@/registry/hooks/lifecycle/use-first-visit/index.ts'),
    {},
  ),
  'hooks-lifecycle-use-hold': lazyRegistryComponent(() => import('@/registry/hooks/lifecycle/use-hold/index.ts'), {}),
  'hooks-lifecycle-use-idle': lazyRegistryComponent(() => import('@/registry/hooks/lifecycle/use-idle/index.ts'), {}),
  'hooks-lifecycle-use-interval': lazyRegistryComponent(
    () => import('@/registry/hooks/lifecycle/use-interval/index.ts'),
    {},
  ),
  'hooks-lifecycle-use-is-mounted': lazyRegistryComponent(
    () => import('@/registry/hooks/lifecycle/use-is-mounted/index.ts'),
    {},
  ),
  'hooks-lifecycle-use-isomorphic-layout-effect': lazyRegistryComponent(
    () => import('@/registry/hooks/lifecycle/use-isomorphic-layout-effect/index.ts'),
    {},
  ),
  'hooks-lifecycle-use-leave-detection': lazyRegistryComponent(
    () => import('@/registry/hooks/lifecycle/use-leave-detection/index.ts'),
    {},
  ),
  'hooks-lifecycle-use-performance-mode': lazyRegistryComponent(
    () => import('@/registry/hooks/lifecycle/use-performance-mode/index.ts'),
    {},
  ),
  'hooks-lifecycle-use-single-effect': lazyRegistryComponent(
    () => import('@/registry/hooks/lifecycle/use-single-effect/index.ts'),
    {},
  ),
  'hooks-lifecycle-use-toggle': lazyRegistryComponent(
    () => import('@/registry/hooks/lifecycle/use-toggle/index.ts'),
    {},
  ),
  'hooks-lifecycle-use-update-effect': lazyRegistryComponent(
    () => import('@/registry/hooks/lifecycle/use-update-effect/index.ts'),
    {},
  ),
  'hooks-lifecycle-use-urgent-update': lazyRegistryComponent(
    () => import('@/registry/hooks/lifecycle/use-urgent-update/index.ts'),
    {},
  ),
}
