/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react'

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>
  demoProps?: Record<string, unknown>
}

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader()
    const exportName = Object.keys(mod).find((key) => typeof mod[key] === 'function' || typeof mod[key] === 'object')
    const Component = mod.default || (exportName ? mod[exportName] : null)

    if (!Component) {
      throw new Error('Registry module has no React component export.')
    }

    if (mod.animations) LazyComponent.animations = mod.animations
    return { default: Component }
  }) as RegistryComponent

  LazyComponent.demoProps = demoProps
  return LazyComponent
}

export const registryComponents: Record<string, RegistryComponent> = {
  'primitives-accordion': lazyRegistryComponent(() => import('@/registry/primitives/accordion/index.tsx'), {}),
  'primitives-alert': lazyRegistryComponent(() => import('@/registry/primitives/alert/index.tsx'), {}),
  'primitives-alert-dialog': lazyRegistryComponent(() => import('@/registry/primitives/alert-dialog/index.tsx'), {}),
  'primitives-aspect-ratio': lazyRegistryComponent(() => import('@/registry/primitives/aspect-ratio/index.tsx'), {}),
  'primitives-autocomplete': lazyRegistryComponent(() => import('@/registry/primitives/autocomplete/index.tsx'), {}),
  'primitives-avatar': lazyRegistryComponent(() => import('@/registry/primitives/avatar/index.tsx'), {}),
  'primitives-badge': lazyRegistryComponent(() => import('@/registry/primitives/badge/index.tsx'), {}),
  'primitives-breadcrumb': lazyRegistryComponent(() => import('@/registry/primitives/breadcrumb/index.tsx'), {}),
  'primitives-button': lazyRegistryComponent(() => import('@/registry/primitives/button/index.tsx'), {}),
  'primitives-calendar': lazyRegistryComponent(() => import('@/registry/primitives/calendar/index.tsx'), {}),
  'primitives-card': lazyRegistryComponent(() => import('@/registry/primitives/card/index.tsx'), {}),
  'primitives-checkbox': lazyRegistryComponent(() => import('@/registry/primitives/checkbox/index.tsx'), {}),
  'primitives-checkbox-group': lazyRegistryComponent(
    () => import('@/registry/primitives/checkbox-group/index.tsx'),
    {},
  ),
  'primitives-collapsible': lazyRegistryComponent(() => import('@/registry/primitives/collapsible/index.tsx'), {}),
  'primitives-combobox': lazyRegistryComponent(() => import('@/registry/primitives/combobox/index.tsx'), {}),
  'primitives-command': lazyRegistryComponent(() => import('@/registry/primitives/command/index.tsx'), {}),
  'primitives-context-menu': lazyRegistryComponent(() => import('@/registry/primitives/context-menu/index.tsx'), {}),
  'primitives-dialog': lazyRegistryComponent(() => import('@/registry/primitives/dialog/index.tsx'), {}),
  'primitives-direction': lazyRegistryComponent(() => import('@/registry/primitives/direction/index.tsx'), {}),
  'primitives-drawer': lazyRegistryComponent(() => import('@/registry/primitives/drawer/index.tsx'), {}),
  'primitives-empty': lazyRegistryComponent(() => import('@/registry/primitives/empty/index.tsx'), {}),
  'primitives-field': lazyRegistryComponent(() => import('@/registry/primitives/field/index.tsx'), {}),
  'primitives-fieldset': lazyRegistryComponent(() => import('@/registry/primitives/fieldset/index.tsx'), {}),
  'primitives-form': lazyRegistryComponent(() => import('@/registry/primitives/form/index.tsx'), {}),
  'primitives-frame': lazyRegistryComponent(() => import('@/registry/primitives/frame/index.tsx'), {}),
  'primitives-group': lazyRegistryComponent(() => import('@/registry/primitives/group/index.tsx'), {}),
  'primitives-input': lazyRegistryComponent(() => import('@/registry/primitives/input/index.tsx'), {}),
  'primitives-input-group': lazyRegistryComponent(() => import('@/registry/primitives/input-group/index.tsx'), {}),
  'primitives-kbd': lazyRegistryComponent(() => import('@/registry/primitives/kbd/index.tsx'), {}),
  'primitives-label': lazyRegistryComponent(() => import('@/registry/primitives/label/index.tsx'), {}),
  'primitives-link': lazyRegistryComponent(() => import('@/registry/primitives/link/index.tsx'), {}),
  'primitives-menu': lazyRegistryComponent(() => import('@/registry/primitives/menu/index.tsx'), {}),
  'primitives-menubar': lazyRegistryComponent(() => import('@/registry/primitives/menubar/index.tsx'), {}),
  'primitives-meter': lazyRegistryComponent(() => import('@/registry/primitives/meter/index.tsx'), {}),
  'primitives-navigation-menu': lazyRegistryComponent(
    () => import('@/registry/primitives/navigation-menu/index.tsx'),
    {},
  ),
  'primitives-number-field': lazyRegistryComponent(() => import('@/registry/primitives/number-field/index.tsx'), {}),
  'primitives-otp-field': lazyRegistryComponent(() => import('@/registry/primitives/otp-field/index.tsx'), {}),
  'primitives-pagination': lazyRegistryComponent(() => import('@/registry/primitives/pagination/index.tsx'), {}),
  'primitives-popover': lazyRegistryComponent(() => import('@/registry/primitives/popover/index.tsx'), {}),
  'primitives-preview-card': lazyRegistryComponent(() => import('@/registry/primitives/preview-card/index.tsx'), {}),
  'primitives-preview-link-card': lazyRegistryComponent(
    () => import('@/registry/primitives/preview-link-card/index.tsx'),
    {},
  ),
  'primitives-progress': lazyRegistryComponent(() => import('@/registry/primitives/progress/index.tsx'), {}),
  'primitives-radio-group': lazyRegistryComponent(() => import('@/registry/primitives/radio-group/index.tsx'), {}),
  'primitives-scroll-area': lazyRegistryComponent(() => import('@/registry/primitives/scroll-area/index.tsx'), {}),
  'primitives-select': lazyRegistryComponent(() => import('@/registry/primitives/select/index.tsx'), {}),
  'primitives-separator': lazyRegistryComponent(() => import('@/registry/primitives/separator/index.tsx'), {}),
  'primitives-sheet': lazyRegistryComponent(() => import('@/registry/primitives/sheet/index.tsx'), {}),
  'primitives-sidebar': lazyRegistryComponent(() => import('@/registry/primitives/sidebar/index.tsx'), {}),
  'primitives-skeleton': lazyRegistryComponent(() => import('@/registry/primitives/skeleton/index.tsx'), {}),
  'primitives-slider': lazyRegistryComponent(() => import('@/registry/primitives/slider/index.tsx'), {}),
  'primitives-spinner': lazyRegistryComponent(() => import('@/registry/primitives/spinner/index.tsx'), {}),
  'primitives-switch': lazyRegistryComponent(() => import('@/registry/primitives/switch/index.tsx'), {}),
  'primitives-table': lazyRegistryComponent(() => import('@/registry/primitives/table/index.tsx'), {}),
  'primitives-tabs': lazyRegistryComponent(() => import('@/registry/primitives/tabs/index.tsx'), {}),
  'primitives-textarea': lazyRegistryComponent(() => import('@/registry/primitives/textarea/index.tsx'), {}),
  'primitives-toast': lazyRegistryComponent(() => import('@/registry/primitives/toast/index.tsx'), {}),
  'primitives-toggle': lazyRegistryComponent(() => import('@/registry/primitives/toggle/index.tsx'), {}),
  'primitives-toggle-group': lazyRegistryComponent(() => import('@/registry/primitives/toggle-group/index.tsx'), {}),
  'primitives-toolbar': lazyRegistryComponent(() => import('@/registry/primitives/toolbar/index.tsx'), {}),
  'primitives-tooltip': lazyRegistryComponent(() => import('@/registry/primitives/tooltip/index.tsx'), {}),
}
