/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryComponent = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
  demoProps?: Record<string, unknown>;
};

function lazyRegistryComponent(
  loader: () => Promise<Record<string, any>>,
  demoProps: Record<string, unknown>,
): RegistryComponent {
  const LazyComponent = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);

    if (!Component) {
      throw new Error('Registry module has no React component export.');
    }

    if (mod.animations) LazyComponent.animations = mod.animations;
    return { default: Component };
  }) as RegistryComponent;

  LazyComponent.demoProps = demoProps;
  return LazyComponent;
}

export const registryComponents: Record<string, RegistryComponent> = {
  "hooks-utils-cache": lazyRegistryComponent(
    () => import("@/registry/utils/cache/index.ts"),
    {},
  ),
  "hooks-utils-cookie": lazyRegistryComponent(
    () => import("@/registry/utils/cookie/index.ts"),
    {},
  ),
  "hooks-utils-event": lazyRegistryComponent(
    () => import("@/registry/utils/event/index.ts"),
    {},
  ),
  "hooks-utils-format-bytes": lazyRegistryComponent(
    () => import("@/registry/utils/format-bytes/index.ts"),
    {},
  ),
  "hooks-utils-format-content": lazyRegistryComponent(
    () => import("@/registry/utils/format-content/index.ts"),
    {},
  ),
  "hooks-utils-format-date": lazyRegistryComponent(
    () => import("@/registry/utils/format-date/index.ts"),
    {},
  ),
  "hooks-utils-format-text": lazyRegistryComponent(
    () => import("@/registry/utils/format-text/index.ts"),
    {},
  ),
  "hooks-utils-is-negative": lazyRegistryComponent(
    () => import("@/registry/utils/is-negative/index.ts"),
    {},
  ),
  "hooks-utils-logger": lazyRegistryComponent(
    () => import("@/registry/utils/logger/index.ts"),
    {},
  ),
  "hooks-utils-range-map": lazyRegistryComponent(
    () => import("@/registry/utils/range-map/index.ts"),
    {},
  ),
  "hooks-utils-sleep": lazyRegistryComponent(
    () => import("@/registry/utils/sleep/index.ts"),
    {},
  ),
};
