/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from 'react';

type RegistryIcon = React.LazyExoticComponent<React.ComponentType<any>> & {
  animations?: Record<string, unknown>;
};

function lazyRegistryIcon(loader: () => Promise<Record<string, any>>) {
  const LazyIcon = React.lazy(async () => {
    const mod = await loader();
    const exportName = Object.keys(mod).find(
      (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object',
    );
    const Component = mod.default || (exportName ? mod[exportName] : null);
    if (!Component) throw new Error('Registry icon has no React export.');
    if (mod.animations) LazyIcon.animations = mod.animations;
    return { default: Component };
  }) as RegistryIcon;
  return LazyIcon;
}

export const iconComponents: Record<string, RegistryIcon> = {
};
