export const DEFAULT_SEEDS = 'Space UI'

export const HISTORICAL_PERSONAS = [
  'Marie Curie',
  'Albert Einstein',
  'Nikola Tesla',
  'Ada Lovelace',
  'Isaac Newton',
  'Galileo Galilei',
  'Charles Darwin',
  'Alan Turing',
  'Grace Hopper',
  'Leonardo da Vinci',
  'Rosalind Franklin',
  'Nelson Mandela',
  'Martin Luther King Jr.',
  'Mahatma Gandhi',
  'Rosa Parks',
  'Malala Yousafzai',
  'Alexander Fleming',
  'Louis Pasteur',
  'Jane Goodall',
  'Stephen Hawking',
  'Thomas Edison',
  'Katherine Johnson',
  'Margaret Hamilton',
  'Tim Berners-Lee',
  'Aristotle',
  'Plato',
  'Socrates',
  'Cleopatra',
  'Julius Caesar',
  'Alexander the Great',
  'Joan of Arc',
  'Winston Churchill',
  'Abraham Lincoln',
  'George Washington',
  'Wolfgang Amadeus Mozart',
  'Ludwig van Beethoven',
  'Vincent van Gogh',
  'Pablo Picasso',
  'William Shakespeare',
  'Mark Twain',
  'Charles Dickens',
  'Jane Austen',
  'Frida Kahlo',
  'Mother Teresa',
  'Florence Nightingale',
  'Amelia Earhart',
  'Harriet Tubman',
  'Susan B. Anthony',
  'Helen Keller',
  'Eleanor Roosevelt',
  'Gautama Buddha',
  'Confucius',
  'Sun Tzu',
  'Ashoka',
  'Genghis Khan',
  'Marco Polo',
  'Christopher Columbus',
  'Vasco da Gama',
  'Ferdinand Magellan',
  'James Cook',
  'Neil Armstrong',
  'Yuri Gagarin',
  'Sally Ride',
  'Valentina Tereshkova',
  'John Glenn',
  'Buzz Aldrin',
  'Michael Collins',
  'Wright Brothers',
  'Henry Ford',
  'Karl Benz',
  'Gottlieb Daimler',
  'Rudolf Diesel',
  'Alexander Graham Bell',
  'Samuel Morse',
  'Guglielmo Marconi',
  'Johannes Gutenberg',
  'Archimedes',
  'Pythagoras',
  'Euclid',
  'Ptolemy',
  'Copernicus',
  'Johannes Kepler',
  'Tycho Brahe',
  'Edwin Hubble',
  'Carl Sagan',
  'Richard Feynman',
  'Max Planck',
  'Niels Bohr',
  'Werner Heisenberg',
  'Erwin Schrödinger',
  'Paul Dirac',
  'Enrico Fermi',
  'J. Robert Oppenheimer',
  'Richard Dawkins',
  'Charles Babbage',
  'John von Neumann',
  'Claude Shannon',
  'Dennis Ritchie',
  'Ken Thompson',
  'Linus Torvalds',
  'Bill Gates',
  'Steve Jobs',
  'Steve Wozniak',
  'Mark Zuckerberg',
  'Jeff Bezos',
  'Elon Musk',
  'Larry Page',
  'Sergey Brin',
  'Jack Ma',
  'Satoshi Nakamoto',
  'Vint Cerf',
  'Bob Kahn',
  'Hedy Lamarr',
  'Mary Shelley',
  'Virginia Woolf',
  'Agatha Christie',
  'J.K. Rowling',
  'George Orwell',
  'Ernest Hemingway',
  'F. Scott Fitzgerald',
  'Leo Tolstoy',
  'Fyodor Dostoevsky',
  'Gabriel Garcia Marquez',
  'Homer',
  'Dante Alighieri',
  'Miguel de Cervantes',
  'Johann Wolfgang von Goethe',
  'Victor Hugo',
  'Ralph Waldo Emerson',
  'Henry David Thoreau',
  'Walt Whitman',
  'Edgar Allan Poe',
  'Emily Dickinson',
  'Maya Angelou',
  'Langston Hughes',
  'Toni Morrison',
  'Zora Neale Hurston',
  'James Baldwin',
  'Ralph Ellison',
  'Richard Wright',
  'W.E.B. Du Bois',
  'Booker T. Washington',
  'Frederick Douglass',
  'Sojourner Truth',
  'Ida B. Wells',
  'Marcus Garvey',
  'Malcolm X',
  'Thurgood Marshall',
  'John Lewis',
  'Jackie Robinson',
  'Muhammad Ali',
  'Pelé',
  'Diego Maradona',
  'Lionel Messi',
  'Cristiano Ronaldo',
  'Michael Jordan',
  'LeBron James',
  'Kobe Bryant',
  'Serena Williams',
  'Venus Williams',
  'Roger Federer',
  'Rafael Nadal',
  'Novak Djokovic',
  'Usain Bolt',
  'Carl Lewis',
  'Jesse Owens',
  'Jim Thorpe',
  'Babe Ruth',
  'Hank Aaron',
  'Willie Mays',
  'Ted Williams',
  'Joe DiMaggio',
  'Mickey Mantle',
  'Sandy Koufax',
  'Bob Gibson',
  'Tom Seaver',
  'Nolan Ryan',
  'Greg Maddux',
  'Pedro Martinez',
  'Randy Johnson',
  'Curt Schilling',
  'Roger Clemens',
  'Barry Bonds',
  'Ken Griffey Jr.',
  'Derek Jeter',
  'Mariano Rivera',
  'David Ortiz',
  'Albert Pujols',
  'Miguel Cabrera',
  'Mike Trout',
  'Mookie Betts',
  'Aaron Judge',
  'Shohei Ohtani',
  'Fernando Tatis Jr.',
  'Juan Soto',
  'Ronald Acuna Jr.',
  'Vladimir Guerrero Jr.',
  'Queen Elizabeth I',
  'Queen Victoria',
  'Catherine the Great',
  'Marie Antoinette',
  'Mary Queen of Scots',
  'Queen Isabella I',
  'Empress Dowager Cixi',
  'Wu Zetian',
  'Hatshepsut',
  'Nefertiti',
  'Boudicca',
  'Zenobia',
  'Catherine de Medici',
  'Maria Theresa',
  'Eleanor of Aquitaine',
  'Anne Boleyn',
  'Mary Tudor',
  'Lady Jane Grey',
  'Elizabeth Bathory',
  'Lucrezia Borgia',
  'Isabella d Este',
  'Caterina Sforza',
  'Artemisia Gentileschi',
  'Sofonisba Anguissola',
  'Lavinia Fontana',
  'Elisabetta Sirani',
  'Fede Galizia',
  'Giovanna Garzoni',
  'Rachel Ruysch',
  'Maria Sibylla Merian',
  'Clara Peeters',
  'Judith Leyster',
  'Mary Beale',
  'Anne Killigrew',
  'Mary Delany',
  'Angelica Kauffman',
  'Mary Moser',
  'Elisabeth Vigee Le Brun',
  'Adelaide Labille-Guiard',
  'Marie-Guillemine Benoist',
  'Constance Mayer',
  'Marguerite Gerard',
  'Pauline Auzou',
  'Henriette Lorimier',
  'Marie-Denise Villers',
  'George Patton',
  'Douglas MacArthur',
  'Dwight D. Eisenhower',
  'Chester W. Nimitz',
  'William Halsey Jr.',
  'Ernest King',
  'George Marshall',
  'Omar Bradley',
  'Henry H. Arnold',
  'Carl Spaatz',
  'Curtis LeMay',
  'James Doolittle',
  'Claire Chennault',
  'Claire Lee Chennault',
  'Simon Bolivar',
  'Jose de San Martin',
  'Bernardo O Higgins',
  'Antonio Jose de Sucre',
  'Francisco de Paula Santander',
  'Jose Gervasio Artigas',
  'Miguel Hidalgo',
  'Jose Maria Morelos',
  'Vicente Guerrero',
  'Agustin de Iturbide',
  'Antonio Lopez de Santa Anna',
  'Benito Juarez',
  'Porfirio Diaz',
  'Francisco I. Madero',
  'Emiliano Zapata',
  'Pancho Villa',
  'Venustiano Carranza',
  'Alvaro Obregon',
  'Plutarco Elias Calles',
  'Lazaro Cardenas',
  'Manuel Avila Camacho',
  'Miguel Aleman Valdes',
  'Adolfo Ruiz Cortines',
  'Adolfo Lopez Mateos',
  'Gustavo Diaz Ordaz',
  'Luis Echeverria',
  'Jose Lopez Portillo',
  'Miguel de la Madrid',
  'Carlos Salinas de Gortari',
  'Ernesto Zedillo',
  'Vicente Fox',
  'Felipe Calderon',
  'Enrique Pena Nieto',
  'Andres Manuel Lopez Obrador',
]
