export interface Interest {
  id: string
  label: string
  emoji: string
}

export const ALL_INTERESTS: Interest[] = [
  { id: 'design', label: 'Design', emoji: '✏️' },
  { id: 'gaming', label: 'Gaming', emoji: '🎮' },
  { id: 'travel', label: 'Travel', emoji: '✈️' },
  { id: 'music', label: 'Music', emoji: '🎵' },
  { id: 'art', label: 'Art', emoji: '🎨' },
  { id: 'coffee', label: 'Coffee', emoji: '☕' },
  { id: 'technology', label: 'Technology', emoji: '💻' },
  { id: 'reading', label: 'Reading', emoji: '📚' },
  { id: 'fitness', label: 'Fitness', emoji: '💪' },
  { id: 'movies', label: 'Movies', emoji: '🎬' },
  { id: 'dancing', label: 'Dancing', emoji: '💃' },
  { id: 'writing', label: 'Writing', emoji: '✍️' },
  { id: 'astronomy', label: 'Astronomy', emoji: '🔭' },
  { id: 'pets', label: 'Pets', emoji: '🐾' },
  { id: 'wine', label: 'Wine Tasting', emoji: '🍷' },
  { id: 'singing', label: 'Singing', emoji: '🎤' },
  { id: 'magic', label: 'Magic Tricks', emoji: '🪄' },
  { id: 'gardening', label: 'Gardening', emoji: '🌱' },
  { id: 'baking', label: 'Baking', emoji: '🧁' },
  { id: 'volunteering', label: 'Volunteering', emoji: '🤝' },
  { id: 'sports', label: 'Athletics', emoji: '🏅' },
  { id: 'space', label: 'Space', emoji: '🚀' },
  { id: 'streetfood', label: 'Street Food', emoji: '🌮' },
  { id: 'cocktails', label: 'Cocktails', emoji: '🍹' },
  { id: 'botany', label: 'Botany', emoji: '🌿' },
  { id: 'astrology', label: 'Astrology', emoji: '♑' },
  { id: 'soccer', label: 'Football', emoji: '⚽' },
  { id: 'keyboards', label: 'Keyboards', emoji: '⌨️' },
  { id: 'bubbletea', label: 'Boba Tea', emoji: '🧋' },
  { id: 'adventure', label: 'Adventure', emoji: '🧭' },
  { id: 'science', label: 'Science', emoji: '🧪' },
  { id: 'diy', label: 'DIY & Tools', emoji: '🧰' },
  { id: 'nightlife', label: 'Nightlife', emoji: '🪩' },
  { id: 'paleontology', label: 'Paleontology', emoji: '🦖' },
  { id: 'wildlife', label: 'Wildlife', emoji: '🦁' },
  { id: 'butterflies', label: 'Entomology', emoji: '🦋' },
  { id: 'birds', label: 'Bird Watching', emoji: '🦉' },
  { id: 'foxes', label: 'Foxes', emoji: '🦊' },
  { id: 'unicorns', label: 'Fantasy', emoji: '🦄' },
  { id: 'flamingos', label: 'Flamingos', emoji: '🦩' },
  { id: 'parrots', label: 'Parrots', emoji: '🦜' },
  { id: 'raccoons', label: 'Raccoons', emoji: '🦝' },
  { id: 'marine-life', label: 'Marine Life', emoji: '🦭' },
  { id: 'cryptocurrency', label: 'Coins & Crypto', emoji: '🪙' },
  { id: 'horology', label: 'Horology', emoji: '⌛' },
  { id: 'weather', label: 'Meteorology', emoji: '⛅' },
  { id: 'hotsprings', label: 'Hot Springs', emoji: '♨️' },
  { id: 'electronics', label: 'Electronics', emoji: '⚡' },
  { id: 'stargazing', label: 'Stargazing', emoji: '⭐' },
  { id: 'winter-sports', label: 'Winter Sports', emoji: '❄️' },
  { id: 'luggage', label: 'Backpacking', emoji: '🧳' },
  { id: 'sparks', label: 'Sparkles', emoji: '✨' },
  { id: 'dinosaurs2', label: 'Sauropods', emoji: '🦕' },
  { id: 'crickets', label: 'Insects', emoji: '🦗' },
  { id: 'outdoors', label: 'Outdoors', emoji: '☀️' },
  { id: 'mindfulness', label: 'Mindfulness', emoji: '☘️' },
  { id: 'beverages', label: 'Juicing', emoji: '🧃' },
  { id: 'healthcare', label: 'Medicine', emoji: '🩺' },
  { id: 'romance', label: 'Dating', emoji: '❤️' },
  { id: 'hedgehogs', label: 'Hedgehogs', emoji: '🦔' },
]
